### ISSUE TITLE
code class="isabelle" expects generated theory name

### ISSUE THREAD

**Issue by makarius** [flatmap/cobra#12]
The theory node of code class="isabelle" is something like code_snippet_1.thy, which means the content needs to start with "theory code_snippet_1 imports Main begin". This is both inconvenient and looks very odd in a presentation.

**Comment by martinring** [comment]
You can set the name by providing an id <code class="isabelle" id="Foo"> would work with "theory Foo imports Main begin"

This should be included in the documentation. It does already work for external files.
