### ISSUE TITLE
Fragile /tmp files

### ISSUE THREAD

**Issue by makarius** [flatmap/cobra#13]
Using global /tmp files without any precautions is a bit fragile. What happens when more than one instance of Cobra is running on the same machine, even by different users?

Moreover, just with one instance, I ran into a situation where /tmp/Haskell.hs contained some old garbage that was not shown in the presentation. Consequently, `ghc-mod` produced errors that were unclear, like

> Info: Multiple declarations of ‘f’
> Declared at: /tmp/Haskell.hs:7:1
> /tmp/Haskell.hs:10:1

These multple occurrences for f where just old junk.

Note that Isabelle/Scala uses `java.nio.file.Files.createTempFile` for the implementation of `Isabelle_System.tmp_file.`

**Comment by martinring** [comment]
You are absolutely right. This was a hack, which I failed to mark with a FIXME comment. Will be addressed in version 1.0.2, which is due tomorrow.

Thanks for pointing this out.
