### ISSUE TITLE
Pointless secure mode

### ISSUE THREAD

**Issue by makarius** [flatmap/cobra#14]
Secure mode for isabelle_process (option -S) does not make much sense: as a local application the user is expected to know what he is doing. Also note that this option has been discontinued in the repository version after Isabelle2016 -- it is not really secure, but may mislead people to think they get a secure system.

Without secure mode in Isabelle2016, it is e.g. possible to use the ML command to demonstrate Isabelle/ML.

**Comment by martinring** [comment]
Sounds reasonable to switch it off. When serving presentations publicly snippets should be read-only anyway by default.
